include: package:flutter_lints/flutter.yaml
linter:
  rules:
    # prefer_const_declarations: true
    prefer_const_constructors_in_immutables: true

analyzer:
  errors:
    unnecessary_library_name: ignore
    use_build_context_synchronously: false