name: sliding_up_panel_custom
description: "A draggable Flutter widget that makes implementing a SlidingUpPanel much easier!"
version: 2.1.0+3
homepage: https://github.com/SiKirillo/sliding_up_panel_custom

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0